on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: Copy main repository files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Disable Admin Protection
      uses: benjefferies/branch-protection-bot@1.0.2
      if: always() 
      with:
        access-token: ${{ secrets.ACCESS_KEY }}
        branch: develop
        enforce_admins: false
      
    - name: Copy main repository files
      id: get-files
      continue-on-error: true
      run: |
        for d in *7Cav*/; do
          if [ -d "${D}"]; then
            if [ $d != "7Cav-Alive-Altis.Altis/" ]
              then
                echo "Starting to process $d"
                ls -d $d/* | grep -v "mission.sqm" | xargs rm -rf
                ls -d ./7Cav-Alive-Altis.Altis/* | grep -v "mission.sqm" | xargs -I '{}' cp -r '{}' ./$d
            fi
          fi
        done
        git config --global user.email "bojan@live.ca"
        git config --global user.name "BojanOnTheInternet"
        
    - name: publish-to-git
      uses: seanmiddleditch/gha-publish-to-git@v1
      with:
        branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_pat: ${{ secrets.ACCESS_KEY }}
            
    - name: Push updated files
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.ACCESS_KEY }}
        branch: develop
        
    - name: Enable Admin Protection
      uses: benjefferies/branch-protection-bot@1.0.2
      if: always() 
      with:
        access-token: ${{ secrets.ACCESS_KEY }}
        branch: develop
        enforce_admins: true
